### Signup request
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "Bibi",
  "email": "bibi_@examplee.com",
  "lastName": "Doe",
  "password": "secret123"
}


### Login request
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "firstName": "Bibi",
  "email": "bibi_@examplee.com",
  "lastName": "Doe",
  "password": "secret123"
}


### Signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "Name": "Nume",
  "email": "email@example.com",
  "password": "123"
}

### Login fără JSON (folosește @RequestParam)
POST http://localhost:8080/api/auth/login?email=email@example.com&password=123

> {% client.global.set("jwt_token", response.body.token); %}

### Test protejat cu JWT
GET http://localhost:8080/api/users/me
Authorization: Bearer {{jwt_token}}
