### Signup request
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "Bibi",
  "email": "bibi_@examplee.com",
  "lastName": "Doe",
  "password": "secret123"
}


### Login request
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "firstName": "Bibi",
  "email": "bibi_@examplee.com",
  "lastName": "Doe",
  "password": "secret123"
}

### Add Post
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "New post",
  "content": "Multe Reply",
  "tags": ["COMPUTER_SCIENCE"],
  "date": "2025-04-27T18:00:00Z",
  "user": {
    "id": "680a75720349e52db7c7b36f"
  }
}

###

### Get All Posts
GET http://localhost:8080/api/posts

###
DELETE http://localhost:8080/api/posts/6807ce689126c428944c0b73

###

### Search Post by Title
GET http://localhost:8080/api/posts/search?title=primul

###

### Filter Post by Tag
GET http://localhost:8080/api/posts/filter?tag=LAW

###

POST http://localhost:8080/api/replies/to-post/680b591ea34bba30fd396797
Content-Type: application/json

{
  "content": "Foarte tare postarea!",
  "user": {
    "id": "680a7b050349e52db7c7b370"
  }
}

###
POST http://localhost:8080/api/replies/to-reply/680b591ea34bba30fd396797
Content-Type: application/json

{
"content": "Fix asta voiam să zic și eu!",
"user": {
"id": "67fe6668b3b5e66421d57732"
}
}


###

### Get All Replies
GET http://localhost:8080/api/replies
