### Add Book
POST http://localhost:8080/api/books
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Ancient History
--boundary
Content-Disposition: form-data; name="author"

Vijay Kumar Singh
--boundary
Content-Disposition: form-data; name="tags"

HISTORY
--boundary
Content-Disposition: form-data; name="imageFile"; filename="hist.jpeg"
Content-Type: image/jpeg

< ./HIST_book_2.jpeg
--boundary
Content-Disposition: form-data; name="userId"

680f6bd9aa1cdd62c8277da1
--boundary--

### GET all books
GET http://localhost:8080/api/books

### FILTER
GET http://localhost:8080/api/books/filter?tag=COMPUTER_SCIENCE

### SEARCH
GET http://localhost:8080/api/books/search?title=Meaa

### DELETE
DELETE http://localhost:8080/api/books/680b5a03cb51032cb5b0bdc1

