### ADD MATERIAL PDF
POST http://localhost:8080/api/materials
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Material CS Law

--boundary
Content-Disposition: form-data; name="description"

Super Material

--boundary
Content-Disposition: form-data; name="type"

PDF

--boundary
Content-Disposition: form-data; name="tags"

COMPUTER_SCIENCE, LAW

--boundary
Content-Disposition: form-data; name="file"; filename="ISS Seminar1.pdf"
Content-Type: application/pdf

< ./ISS Seminar1.pdf

--boundary
Content-Disposition: form-data; name="userId"

680a75720349e52db7c7b36f
--boundary


### ADD MATERIAL DOCX
POST http://localhost:8080/api/materials
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Material docx Medicine

--boundary
Content-Disposition: form-data; name="description"

Super Material Medicine

--boundary
Content-Disposition: form-data; name="type"

DOCX

--boundary
Content-Disposition: form-data; name="tags"

MEDICINE

--boundary
Content-Disposition: form-data; name="file"; filename="document.docx"
Content-Type: application/docx

< ./docx.docx

--boundary
Content-Disposition: form-data; name="userId"

680a75720349e52db7c7b36f
--boundary



### ADD MATERIAL PNG
POST http://localhost:8080/api/materials
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Material png Medicine

--boundary
Content-Disposition: form-data; name="description"

Super Material Medicine poza png …

--boundary
Content-Disposition: form-data; name="type"

PNG

--boundary
Content-Disposition: form-data; name="tags"

MEDICINE, COMPUTER_SCIENCE

--boundary
Content-Disposition: form-data; name="file"; filename="logo.png"
Content-Type: image/png

< ./logo.png

--boundary
Content-Disposition: form-data; name="userId"

680a75720349e52db7c7b36f

--boundary--



### ADD MATERIAL JPG
POST http://localhost:8080/api/materials
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="name"

Material jpg LAW

--boundary
Content-Disposition: form-data; name="description"

Super Material LAW poza png …

--boundary
Content-Disposition: form-data; name="type"

JPG

--boundary
Content-Disposition: form-data; name="tags"

LAW

--boundary
Content-Disposition: form-data; name="file"; filename="img.jpg"
Content-Type: image/jpg

< ./image.jpg

--boundary
Content-Disposition: form-data; name="userId"

680a75720349e52db7c7b36f

--boundary--


### GET all materials
GET http://localhost:8080/api/materials

### DELETE material
DELETE http://localhost:8080/api/materials/6808b8423c77895336626f25

### FILTER
GET http://localhost:8080/api/materials/filter?tag=COMPUTER_SCIENCE

### SEARCH
GET http://localhost:8080/api/materials/search?name=Prelegere Java Avansat

### Add Rating
PUT http://localhost:8080/api/materials/rating?materialId=680b4f125520a75510580edc&rating=3

### Update Material
PUT http://localhost:8080/api/materials/update?materialId=6808b8423c77895336626f25&description=Nou&tags=LAW
